### ISSUE TITLE
Is this issue tracker still active?

### ISSUE THREAD

**Issue by xaduha** [cloudkeep/barbican#762]

**Comment by jfwood** [comment]
Hello xaduha, the cloudkeep/barbican repository is no longer maintained or active, as Barbican is not an OpenStack project. Please instead refer to the openstack/barbican repository. Also, please not that to report bugs you would now utilize https://bugs.launchpad.net/barbican/+bugs, and to see and review active issues please see https://review.openstack.org/#/q/is:watched+is:open+barbican
